config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[index new create show destroy edit update] do
    scope module: :users do
      resources :favorites, only: %i[index]
    end

    resource :relationships, only: %i[create destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :tweets, only: %i[index new create show destroy edit update] do
    resource :favorites, only: %i[create destroy]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '*path', controller: 'application', action: 'render_404'
  root to: 'sessions#new'
end

app/models/tweet.rb
# frozen_string_literal: true

class Tweet < ApplicationRecord
  validates :user, presence: true
  validates :title, presence: true, length: { maximum: 20 }
  validates :content, presence: true, length: { maximum: 140 }

  belongs_to :user
  has_many :favorites, dependent: :destroy

  def favorited_by?(target_user_id)
    favorites.any? { |favorite| favorite.user_id == target_user_id }
  end
end

app/controllers/admin/tweets_controller.rb
module Admin
  # Controller for managing tweets by administrators.
  class TweetsController < ApplicationController
    before_action :check_admin

    # GET /admin/tweets
    def index
      @tweets = Tweet.all.preload(:user, :favorites)
    end

    # DELETE admin/tweets/:id
    def destroy
      @tweet = Tweet.find(params[:id])
      if @tweet.destroy
        flash[:notice] = '削除に成功しました'
        redirect_to admin_tweets_path
      else
        flash.now[:alert] = '削除に失敗しました'
        render admin_tweets_path
      end
    end
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :check_logged_in, only: %i[index show new create]
  before_action -> { check_edit_authority(Tweet.find(params[:id]).user_id) }, only: %i[edit update destroy]

  # GET /tweets
  def index
    @tweets = Tweet.all.preload(:user, :favorites).order(created_at: :desc)
  end

  # GET /tweets/:id
  def show
    @tweet = Tweet.find(params[:id])
    @user = @tweet.user
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # POST /tweets
  def create
    @tweet = Tweet.new(tweet_params.merge(user: current_user))
    if @tweet.save
      flash[:notice] = '投稿に成功しました'
      redirect_to tweets_path
    else
      flash.now[:alert] = '投稿に失敗しました'
      render :new
    end
  end

  # GET /tweets/:id/edit
  def edit
    @tweet = current_user.tweets.find(params[:id])
    @user = @tweet.user
  end

  # PUT /tweets/:id
  def update
    @tweet = Tweet.find(params[:id])
    if @tweet.update(tweet_params)
      flash[:notice] = '修正に成功しました'
      redirect_to tweets_path
    else
      flash.now[:alert] = '修正に失敗しました'
      render :edit
    end
  end

  # DELETE /tweets/:id
  def destroy
    @tweet = current_user.tweets.find(params[:id])
    if @tweet.destroy
      flash[:notice] = '削除に成功しました'
      redirect_to tweets_path
    else
      flash.now[:alert] = '削除に失敗しました'
      render tweets_path
    end
  end

  private

  def tweet_params
    params.require(:tweet).permit(:title, :content)
  end
end

app/views/tweets/edit.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "custom/tweet-delete-modal" %>
<% end %>

<section class="is-flex is-flex-direction-column is-justify-content-center is-align-items-center" style="height: calc(100vh - 96px);">
  <div class="box" style="width: 600px;">
    <!-- boxのタイトル -->
    <div class="content">
      <div class="block">
        <h2>ひとりごと編集</h2>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
    </div>

    <!-- ひとりごと編集フォーム -->
    <%= form_with model: @tweet, url: tweet_path, data: { turbo: "false" } do |f| %>
      <div class="field">
        <label class="label">タイトル</label>
        <div class="control">
          <%= f.text_field :title, class: "input is-black", placeholder: "20字以内" %>
        </div>
      </div>
      <div class="block">
        <div class="field">
          <label class="label">本文</label>
          <div class="control">
            <%= f.text_area :content, class: "textarea is-black", placeholder: "140字以内", rows: 4 %></td>
          </div>
        </div>
      </div>
      <div class="block">
        <div class="control">
          <%= f.submit '変更する', class: "button is-link is-fullwidth", style: "background-color: #6a994e" %>
        </div>
      </div>
      <div class="block">
        <%= link_to "キャンセル", :back, class: "button is-fullwidth has-text-white", style: "background-color: #bc4749" %>
      </div>
    <% end %>

    <!-- ひとりごと削除ボタン -->
    <div class="block pt-5">
      <div class="has-background-grey-lighter" style="height: 2px;"></div>
    </div>
    <div class="block">
      <button class="button is-fullwidth is-black" id="tweet-delete-button">ひとりごと削除</button>
    </div>

    <!-- フラッシュメッセージ -->
    <div class="mt-5">
      <div class="levlel">
        <% if flash[:alert] %>
          <div class="notification is-danger is-light has-text-centered">
            <%= flash[:alert] %> 
            <% @tweet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- モーダルウインドウ -->
    <div class="modal" id="tweet-delete-modal-window">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="column is-6 is-offset-3">
          <div class="box">
            <div class="content-level">
              <div class="level-left">
                <button class="delete" aria-label="close" id="close-tweet-delete"></button>
              </div>
              <div class="level-item">
                <p>ひとりごとを削除しますか？</p>
              </div>
            </div>
            <div class="level mt-4">
              <div class="level-item">
                <%= button_to "はい", tweet_path(@tweet.id), method: :delete, class: "button is-rounded is-white is-inverted has-text-weight-semibold" %>
              </div>
              <div class="level-item">
                <button class="button is-rounded has-text-weight-semibold" aria-label="close" id="cancel-tweet-delete">いいえ</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/tweets/index.html.erb
<main class="columns p-1 m-0">
  <!-- メニュー -->
  <div class="column is-one-third">
    <div class="box">
      <aside class="menu">
        <div class="menu-label is-size-6 has-text-weight-semibold has-text-black">
          <p>＜ひとりごと一覧メニュー＞</p>
        </div>
        <ul class="menu-list">
          <li><a href="<%= tweets_path() %>">タイムライン</a></li>
        </ul>
      </aside>
    </div>
    <div class="lavel mt-5">
      <% if flash[:notice] %>
        <div class="notification is-success is-light has-text-centered"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="notification is-danger is-light has-text-centered"><%= flash[:alert] %></div>
      <% end %>
    </div>
  </div>

  <!-- タイムライン -->
  <div class="column">
    <div class="box">
      <div class="content m-0 pl-4">
        <h4>タイムライン</h4>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
      <% @tweets.each do |tweet| %>
      <article class="media m-0 p-0">
        <div class="media-content">
          <div class="tags pl-1 mb-0">
            <span class="tag mb-0 is-white is-size-6 has-text-weight-semibold" style="color: #386641">
              <p><%= tweet.user.name %></p>
            </span>
            <span class="tag mb-0 is-white is-size-6 " style="color: #7d7d7d">
              <p><%= tweet.user.email %></p>
            </span>
          </div>
          <div class="block pl-4 mb-1">
            <p class="content mb-0 is-size-6"><%= tweet.updated_at.strftime("%Y年%_m月%_d日 %_H:%M") %></p>           
            <p class="content mb-0 is-size-6 is-underlined"><%= tweet.title %></p>
            <p class="content mb-0 is-size-6" ><%= tweet.content %></p>
          </div>
          <div class="content is-mobile pl-4 mb-2">
            <% if tweet.favorited_by?(current_user.id) %>
              <%= button_to "いいね #{tweet.favorites.size}", tweet_favorites_path(tweet.id), method: :delete, class: "button is-small has-text-weight-semibold has-text-white", style: "background-color: #6a994e" %>
            <% else %>
              <%= button_to "いいね #{tweet.favorites.size}", tweet_favorites_path(tweet.id), method: :post, class: "button is-small is-outlined has-text-weight-semibold", style: "color: #6a994e; border-color: #6a994e;" %>
            <% end %>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</main>

app/views/tweets/new.html.erb
<section class="is-flex is-flex-direction-column is-justify-content-center is-align-items-center" style="height: calc(100vh - 105px);">
  <div class="box" style="width: 600px;">
    <!-- boxのタイトル -->
    <div class="content">
      <div class="block">
        <h2>ひとりごと投稿</h2>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
    </div>

    <!-- 投稿フォーム -->
    <%= form_with model: @tweet, url: tweets_path, data: { turbo: "false" } do |f| %>
      <div class="field">
        <label class="label">タイトル</label>
        <div class="control">
          <%= f.text_field :title, class: "input is-black", placeholder: "20字以内" %>
        </div>
      </div>
      <div class="block">
        <div class="field">
          <label class="label">本文</label>
          <div class="control">
            <%= f.text_area :content, class: "textarea is-black", placeholder: "140字以内", rows: 4 %></td>
          </div>
        </div>
      </div>
      <div class="block">
        <div class="control">
          <%= f.submit '送信', class: "button is-link is-fullwidth", style: "background-color: #6a994e" %>
        </div>
      </div>
      <div class="block">
        <div class="control">
          <%= link_to "キャンセル", :back, class: "button is-link is-fullwidth", style: "background-color: #bc4749" %>
        </div>
      </div>
    <% end %>

    <!-- フラッシュメッセージ -->
    <div class="mt-5">
      <div class="levlel">
        <% if flash[:alert] %>
          <div class="notification is-danger is-light has-text-centered">
            <%= flash[:alert] %> 
            <% @tweet.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/tweets/show.html.erb
<h1>ツイート</h1>
<p><span>メールアドレス： </span><%= @user.email %></p>
<p><span>タイトル: </span><%= @tweet.title %></p>
<p><span>ツイート: </span><%= @tweet.content %></p>

<% if session[:user_id] == @tweet.user_id %>
  <%= button_to "ツイート修正", edit_tweet_path(@tweet.id), method: :get %>
  <%= button_to "ツイート削除", tweet_path(@tweet.id), method: :delete %>
<% end %>