config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[index new create show destroy edit update] do
    scope module: :users do
      resources :favorites, only: %i[index]
    end

    resource :relationships, only: %i[create destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :tweets, only: %i[index new create show destroy edit update] do
    resource :favorites, only: %i[create destroy]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '*path', controller: 'application', action: 'render_404'
  root to: 'sessions#new'
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true, length: { maximum: 15 }
  validates :email, presence: true
  validates :password, presence: true

  has_many :tweets, dependent: :destroy
  has_many :favorites, dependent: :destroy
  # <Userモデルのインスタンス>.favorite_tweetsでいいねしたツイートを取得する
  has_many :favorite_tweets, through: :favorites, source: :tweet, dependent: :destroy

  # フォローする側のUserからみたRelationshipをactive_relationshipとする
  has_many :active_relationships, class_name: 'Relationship', foreign_key: :following_id, dependent: :destroy
  # 中間テーブルを介してUser(フォローされた側)を集めることを「followings」と定義
  has_many :followings, through: :active_relationships, source: :follower

  # フォローされる側のUserからみたRelationshipをpassive_relationshipとする
  has_many :passive_relationships, class_name: 'Relationship', foreign_key: :follower_id, dependent: :destroy
  # 中間テーブルを介してUser(フォローする側)を集めることを「followers」と定義
  has_many :followers, through: :passive_relationships, source: :following

  def followed_by?(target_user_id)
    # フォローしようとしているユーザー(レシーバー)がフォローされているユーザー(つまりpassive)の中から、引数に渡されたユーザー(自分)がいるかどうかを調べる
    passive_relationships.find_by(following_id: target_user_id).present?
  end
end

app/controllers/admin/users_controller.rb
module Admin
  # Controller for managing users by administrators.
  class UsersController < ApplicationController
    before_action :check_admin

    # GET /admin/users
    def index
      @users = User.all
    end

    # DELETE /admin/users/:id
    def destroy
      @user = User.find(params[:id])
      if @user.destroy
        flash[:notice] = '削除しました'
        redirect_to admin_users_path
      else
        flash[:alert] = '削除に失敗しました'
        render admin_users_path
      end
    end
  end
end

app/controllers/users/favorites_controller.rb
module Users
  # Controller for managing favorite lists of users.
  class FavoritesController < ApplicationController
    before_action :check_logged_in, only: %i[index]

    # GET /users/:id/favorites
    def index
      @user = User.find(params[:user_id])
      @tweets = Tweet.eager_load(:user, :favorites).where(favorites: { user_id: @user.id })
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :check_logged_in, only: %i[index show follows followers]
  before_action -> { check_edit_authority(params[:id].to_i) }, only: %i[edit update destroy]

  # GET /users
  def index
    @users = User.all
  end

  # GET /users/:id
  def show
    @user = User.find(params[:id])
    @tweets = Tweet.eager_load(:user, :favorites).where(user: { id: params[:id] })
  end

  # GET /users/new
  def new
    @user = User.new
    render :layout => 'header'
  end

  # POST /users
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = '登録に成功しました'
      redirect_to '/login'
    else
      flash.now[:alert] = '登録に失敗しました'
      render '/users/new', layout: 'header'
    end
  end

  # DELETE /users/:id
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      flash[:notice] = 'アカウントを削除しました'
      redirect_to '/login'
    else
      flash[:alert] = 'アカウントの削除に失敗しました'
      redirect_to '/users'
    end
  end

  # GET /users/:id/edit
  def edit
    @user = User.find(params[:id])
  end

  # PUT /users/:id
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:notice] = 'アカウント情報の変更に成功しました'
      redirect_to '/users'
    else
      flash.now[:alert] = 'アカウント情報の変更に失敗しました'
      render :edit
    end
  end

  # GET /users/:id/follows
  def follows
    @user = User.find(params[:id])
    @following_users = @user.followings
  end

  # GET /users/:id/followers
  def followers
    @user = User.find(params[:id])
    @follower_users = @user.followers
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password)
    # require(:user)はリクエストパラメータの中から:userキーに関連付けられた値を取得
    # permit(:name, :email, :password)は:name, :email, :passwordキーのみ許可
  end
end

app/views/users/edit.html.erb
<% content_for :js do %>
  <%= javascript_import_module_tag "custom/user-delete-modal" %>
<% end %>

<section class="is-flex is-flex-direction-column is-justify-content-center is-align-items-center" style="height: calc(100vh - 96px);">
  <div class="box" style="width: 600px;">
    <!-- boxのタイトル -->
    <div class="content">
      <div class="block">
        <h2>アカウント編集</h2>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
    </div>

    <!-- アカウント編集フォーム -->
    <%= form_with model: @user, url: user_path, data: { turbo: "false" } do |f| %>
      <div class="field">
        <label class="label">アカウント名</label>
        <div class="control">
          <%= f.text_field :name, class: "input is-black", placeholder: "15字以内" %>
        </div>
      </div>    
      <div class="field">
        <label class="label">メールアドレス</label>
        <div class="control">
          <%= f.email_field :email, class: "input is-black", placeholder: "sample@example.com" %>
        </div>
      </div>
      <div class="block">
        <div class="field">
          <label class="label">パスワード</label>
          <div class="control">
            <%= f.password_field :password, class: "input is-black", placeholder: "********" %>
          </div>
        </div>
      </div>
      <div class="block">
        <%= f.submit '変更する', class: "button is-fullwidth has-text-white", style: "background-color: #6a994e" %>
      </div>
      <div class="block">
        <%= link_to "キャンセル", :back, class: "button is-fullwidth has-text-white", style: "background-color: #bc4749" %>
      </div>
    <% end %>

    <!-- アカウント削除ボタン -->
    <div class="block pt-5">
      <div class="has-background-grey-lighter" style="height: 2px;"></div>
    </div>
    <div class="block">
      <button class="button is-fullwidth is-black" id="user-delete-button">アカウント削除</button>
    </div>

    <!-- フラッシュメッセージ -->
    <div class="mt-5">
      <div class="levlel">
        <% if flash[:alert] %>
          <div class="notification is-danger is-light has-text-centered">
            <%= flash[:alert] %> 
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>

    <!-- モーダルウインドウ -->
    <div class="modal" id="user-delete-modal-window">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="column is-6 is-offset-3">
          <div class="box">
            <div class="content-level">
              <div class="level-left">
                <button class="delete" aria-label="close" id="close-user-delete"></button>
              </div>
              <div class="level-item">
                <p>アカウントを削除しますか？</p>
              </div>
            </div>
            <div class="level mt-4">
              <div class="level-item">
                <%= button_to "はい", user_path(current_user.id), method: :delete, class: "button is-rounded is-white is-inverted has-text-weight-semibold" %>
              </div>
              <div class="level-item">
                <button class="button is-rounded has-text-weight-semibold" aria-label="close" id="cancel-user-delete">いいえ</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/users/favorites.html.erb
<main class= "columns p-1 m-0">
  <!-- ユーザー情報 -->
  <div class="column is-one-third">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content pl-4">
            <p class="content mb-0 is-size-4 has-text-weight-semibold" style="color: #386641"><%= @user.name %></p>           
            <p class="content mb-0 is-size-6 has-text-weight-semibold" style="color: #7d7d7d"><%= @user.email %></p>
          </div>
          <div class="content">
            <nav class="level">
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">投稿</p>
                  <p class="title is-size-5" ><%= @user.tweets.size %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロー</p>
                  <p class="title is-size-5">***</p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロワー</p>
                  <p class="title is-size-5">***</p>
                </div>
              </div>
            </nav>
          </div>
        </div>  
      </article>
    </div>
    <div class="box">
      <aside class="menu">
        <div class="menu-label is-size-6 has-text-weight-semibold has-text-black">
          <p>＜メニュー＞</p>
        </div>
        <ul class="menu-list">
          <li><a href="<%= user_path(params[:id]) %>">投稿</a></li>
          <li><a href="<%= favorites_user_path(params[:id]) %>">いいね一覧</a></li>
          <li><a href="#">フォローリスト</a></li>
          <li><a href="#">フォロワーリスト</a></li>
        </ul>
      </aside>
    </div>
    <div class="lavel mt-5">
      <% if flash[:notice] %>
        <div class="notification is-success is-light has-text-centered"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="notification is-danger is-light has-text-centered"><%= flash[:alert] %></div>
      <% end %>
    </div>
  </div>
  <!-- ユーザーの投稿 -->
  <div class="column">
    <div class="box">
      <div class="content m-0 pl-4">
        <h4>いいね一覧</h4>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
      <% @tweets.each do |tweet| %>
      <article class="media m-0 p-0">
        <div class="media-content">
          <nav class="level mb-0 mt-1">
            <div class="level-left">
              <div class="tags pl-1 mb-0">
                <span class="tag mb-0 is-white is-size-6 has-text-weight-semibold" style="color: #386641">
                  <p><%= tweet.user.name %></p>
                </span>
                <span class="tag mb-0 is-white is-size-6 " style="color: #7d7d7d">
                  <p><%= tweet.user.email %></p>
                </span>
              </div>
            </div>
            <% if session[:user_id] == tweet.user_id %>
              <div class="level-right">
                <%= button_to "編集・削除", edit_tweet_path(tweet.id), method: :get, class: "button is-small is-outlined has-text-weight-semibold", style: "color: #7d7d7d; border-color: #7d7d7d;" %>
              </div>
            <% end %>
          </nav>
          <div class="content pl-4 mb-1">
            <p class="content mb-0 is-size-6"><%= tweet.updated_at.strftime("%Y年%_m月%_d日 %_H:%M") %></p>           
            <p class="content mb-0 is-size-6 is-underlined"><%= tweet.title %></p>
            <p class="content mb-0 is-size-6" ><%= tweet.content %></p>
          </div>
          <div class="content is-mobile pl-4 mb-2">
            <% if tweet.favorited_by?(current_user.id) %>
              <%= button_to "いいね #{tweet.favorites.size}", tweet_favorites_path(tweet.id), method: :delete, class: "button is-small has-text-weight-semibold has-text-white", style: "background-color: #6a994e" %>
            <% else %>
              <%= button_to "いいね #{tweet.favorites.size}", tweet_favorites_path(tweet.id), method: :post, class: "button is-small is-outlined has-text-weight-semibold", style: "color: #6a994e; border-color: #6a994e;" %>
            <% end %>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</main>

app/views/users/followers.html.erb
<main class="columns p-1 m-0">
  <!-- ユーザー情報 -->
  <div class="column is-one-third">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content pl-4">
            <p class="content mb-0 is-size-4 has-text-weight-semibold" style="color: #386641"><%= @user.name %></p>           
            <p class="content mb-0 is-size-6 has-text-weight-semibold" style="color: #7d7d7d"><%= @user.email %></p>
          </div>
          <div class="content">
            <nav class="level">
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">投稿</p>
                  <p class="title is-size-5" ><%= @user.tweets.size %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロー</p>
                  <p class="title is-size-5" ><%= @user.followings.size %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロワー</p>
                  <p class="title is-size-5" ><%= @user.followers.size %></p>
                </div>
              </div>
            </nav>
          </div>
        </div>  
      </article>
    </div>
    <div class="box">
      <aside class="menu">
        <div class="menu-label is-size-6 has-text-weight-semibold has-text-black">
          <p>＜メニュー＞</p>
        </div>
        <ul class="menu-list">
          <li><a href="<%= user_path(params[:id]) %>">投稿</a></li>
          <li><a href="<%= user_favorites_path(params[:id]) %>">いいね一覧</a></li>
          <li><a href="<%= follows_user_path(params[:id]) %>">フォローリスト</a></li>
          <li><a href="<%= followers_user_path(params[:id]) %>">フォロワーリスト</a></li>
        </ul>
      </aside>
    </div>
    <div class="lavel mt-5">
      <% if flash[:notice] %>
        <div class="notification is-success is-light has-text-centered"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="notification is-danger is-light has-text-centered"><%= flash[:alert] %></div>
      <% end %>
    </div>
  </div>

  <!-- フォロワーリスト -->
  <div class="column">
    <div class="box">
      <div class="content m-0 pl-4">
        <h4>フォロワーリスト</h4>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
      <% @follower_users.each do |user| %>
      <article class="media m-1 p-0">
        <div class="media-content">
          <div class="columns">
            <div class="column is-10 pl-4">
              <div class="tags">
                <span class="tag is-white is-size-6 has-text-weight-semibold" style="color: #386641">
                  <p><%= user.name %></p>
                </span>
                <span class="tag is-white is-size-6" style="color: #7d7d7d">
                  <%=link_to user.email, user_path(user.id), style: "color: #7d7d7d" %></p>
                </span>
              </div>
            </div>
            <div class="column is-2 ">
              <% if current_user&.id != user.id %>
                <% if user.followed_by?(current_user&.id) %>
                  <%= button_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "button is-small has-text-weight-semibold has-text-white mt-1", style: "background-color: #6a994e" %>
                <% else %>
                  <%= button_to "フォロー", user_relationships_path(user.id), method: :post, class: "button is-small is-outlined has-text-weight-semibold mt-1", style: "color: #6a994e; border-color: #6a994e" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</main>

app/views/users/follows.html.erb
<main class="columns p-1 m-0">
  <!-- ユーザー情報 -->
  <div class="column is-one-third">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content pl-4">
            <p class="content mb-0 is-size-4 has-text-weight-semibold" style="color: #386641"><%= @user.name %></p>           
            <p class="content mb-0 is-size-6 has-text-weight-semibold" style="color: #7d7d7d"><%= @user.email %></p>
          </div>
          <div class="content">
            <nav class="level">
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">投稿</p>
                  <p class="title is-size-5" ><%= @user.tweets.size %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロー</p>
                  <p class="title is-size-5" ><%= @user.followings.size %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロワー</p>
                  <p class="title is-size-5" ><%= @user.followers.size %></p>
                </div>
              </div>
            </nav>
          </div>
        </div>  
      </article>
    </div>
    <div class="box">
      <aside class="menu">
        <div class="menu-label is-size-6 has-text-weight-semibold has-text-black">
          <p>＜メニュー＞</p>
        </div>
        <ul class="menu-list">
          <li><a href="<%= user_path(params[:id]) %>">投稿</a></li>
          <li><a href="<%= user_favorites_path(params[:id]) %>">いいね一覧</a></li>
          <li><a href="<%= follows_user_path(params[:id]) %>">フォローリスト</a></li>
          <li><a href="<%= followers_user_path(params[:id]) %>">フォロワーリスト</a></li>
        </ul>
      </aside>
    </div>
    <div class="lavel mt-5">
      <% if flash[:notice] %>
        <div class="notification is-success is-light has-text-centered"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="notification is-danger is-light has-text-centered"><%= flash[:alert] %></div>
      <% end %>
    </div>
  </div>

  <!-- フォローリスト -->
  <div class="column">
    <div class="box">
      <div class="content m-0 pl-4">
        <h4>フォローリスト</h4>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
      <% @following_users.each do |user| %>
      <article class="media m-1 p-0">
        <div class="media-content">
          <div class="columns">
            <div class="column is-10 pl-4">
              <div class="tags">
                <span class="tag is-white is-size-6 has-text-weight-semibold" style="color: #386641">
                  <p><%= user.name %></p>
                </span>
                <span class="tag is-white is-size-6" style="color: #7d7d7d">
                  <%=link_to user.email, user_path(user.id), style: "color: #7d7d7d" %></p>
                </span>
              </div>
            </div>
            <div class="column is-2 ">
              <% if current_user&.id != user.id %>
                <% if user.followed_by?(current_user&.id) %>
                  <%= button_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "button is-small has-text-weight-semibold has-text-white mt-1", style: "background-color: #6a994e" %>
                <% else %>
                  <%= button_to "フォロー", user_relationships_path(user.id), method: :post, class: "button is-small is-outlined has-text-weight-semibold mt-1", style: "color: #6a994e; border-color: #6a994e" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</main>

app/views/users/index.html.erb
<main class="columns p-1 m-0">
  <!-- メニュー -->
  <div class="column is-one-third">
    <div class="box">
      <aside class="menu">
        <div class="menu-label is-size-6 has-text-weight-semibold has-text-black">
          <p>＜メニュー＞</p>
        </div>
        <ul class="menu-list">
          <li><a href="<%= users_path() %>">ユーザーリスト</a></li>
        </ul>
      </aside>
    </div>
    <div class="lavel mt-5">
      <% if flash[:notice] %>
        <div class="notification is-success is-light has-text-centered"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="notification is-danger is-light has-text-centered"><%= flash[:alert] %></div>
      <% end %>
    </div>
  </div>

  <!-- ユーザーリスト -->
  <div class="column">
    <div class="box">
      <div class="content m-0 pl-4">
        <h4>ユーザーリスト</h4>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
      <% @users.each do |user| %>
      <article class="media m-1 p-0">
        <div class="media-content">
          <div class="columns">
            <div class="column is-10 pl-4">
              <div class="tags">
                <span class="tag is-white is-size-6 has-text-weight-semibold" style="color: #386641">
                  <p><%= user.name %></p>
                </span>
                <span class="tag is-white is-size-6" style="color: #7d7d7d">
                  <%=link_to user.email, user_path(user.id), style: "color: #7d7d7d" %></p>
                </span>
              </div>
            </div>
            <div class="column is-2 ">
              <% if current_user&.id != user.id %>
                <% if user.followed_by?(current_user&.id) %>
                  <%= button_to "フォロー中", user_relationships_path(user.id), method: :delete, class: "button is-small has-text-weight-semibold has-text-white mt-1", style: "background-color: #6a994e" %>
                <% else %>
                  <%= button_to "フォロー", user_relationships_path(user.id), method: :post, class: "button is-small is-outlined has-text-weight-semibold mt-1", style: "color: #6a994e; border-color: #6a994e" %>
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</main>

app/views/users/new.html.erb
<section class="is-flex is-flex-direction-column is-justify-content-center is-align-items-center" style="height: calc(100vh - 64px);">
  <div class="box" style="width: 600px;">
    <div class="content">
      <div class="block">
        <h2>会員登録</h2>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
    </div>

    <%= form_with model: @user, url: users_path, data: { turbo: "false" } do |f| %>
      <div class="field">
        <label class="label">アカウント名</label>
        <div class="control">
          <%= f.text_field :name, class: "input is-black", placeholder: "15字以内" %>
        </div>
      </div>

      <div class="field">
        <label class="label">メールアドレス</label>
        <div class="control">
          <%= f.email_field :email, class: "input is-black", placeholder: "sample@example.com" %>
        </div>
      </div>

      <div class="block">
        <div class="field">
          <label class="label">パスワード</label>
          <div class="control">
            <%= f.password_field :password, class: "input is-black", placeholder: "********" %>
          </div>
        </div>
      </div>

      <div class="block">
        <div class="control">
          <%= f.submit '新規会員登録', class: "button is-link is-fullwidth", style: "background-color: #6a994e" %>
        </div>
      </div>
    <% end %>

    <div class="mt-5">
      <div class="levlel">
        <% if flash[:alert] %>
          <div class="notification is-danger is-light has-text-centered">
            <%= flash[:alert] %> 
            <% @user.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<main class= "columns p-1 m-0">
  <!-- ユーザー情報 -->
  <div class="column is-one-third">
    <div class="box">
      <article class="media">
        <div class="media-content">
          <div class="content pl-4">
            <p class="content mb-0 is-size-4 has-text-weight-semibold" style="color: #386641"><%= @user.name %></p>           
            <p class="content mb-0 is-size-6 has-text-weight-semibold" style="color: #7d7d7d"><%= @user.email %></p>
          </div>
          <div class="content">
            <nav class="level">
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">投稿</p>
                  <p class="title is-size-5" ><%= @user.tweets.size %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロー</p>
                  <p class="title is-size-5" ><%= @user.followings.size %></p>
                </div>
              </div>
              <div class="level-item has-text-centered">
                <div>
                  <p class="heading is-size-7">フォロワー</p>
                  <p class="title is-size-5" ><%= @user.followers.size %></p>
                </div>
              </div>
            </nav>
          </div>
        </div>  
      </article>
    </div>
    <div class="box">
      <aside class="menu">
        <div class="menu-label is-size-6 has-text-weight-semibold has-text-black">
          <p>＜メニュー＞</p>
        </div>
        <ul class="menu-list">
          <li><a href="<%= user_path(params[:id]) %>">投稿</a></li>
          <li><a href="<%= user_favorites_path(params[:id]) %>">いいね一覧</a></li>
          <li><a href="<%= follows_user_path(params[:id]) %>">フォローリスト</a></li>
          <li><a href="<%= followers_user_path(params[:id]) %>">フォロワーリスト</a></li>
        </ul>
      </aside>
    </div>
    <div class="lavel mt-5">
      <% if flash[:notice] %>
        <div class="notification is-success is-light has-text-centered"><%= flash[:notice] %></div>
      <% elsif flash[:alert] %>
        <div class="notification is-danger is-light has-text-centered"><%= flash[:alert] %></div>
      <% end %>
    </div>
  </div>
  <!-- ユーザーの投稿 -->
  <div class="column">
    <div class="box">
      <div class="content m-0 pl-4">
        <h4>投稿</h4>
        <div class="has-background-grey-lighter" style="height: 2px;"></div>
      </div>
      <% @tweets.each do |tweet| %>
      <article class="media m-0 p-0">
        <div class="media-content">
          <nav class="level mb-0 mt-1">
            <div class="level-left">
              <div class="tags pl-1 mb-0">
                <span class="tag mb-0 is-white is-size-6 has-text-weight-semibold" style="color: #386641">
                  <p><%= tweet.user.name %></p>
                </span>
                <span class="tag mb-0 is-white is-size-6 " style="color: #7d7d7d">
                  <p><%= tweet.user.email %></p>
                </span>
              </div>
            </div>
            <% if session[:user_id] == tweet.user_id %>
              <div class="level-right">
                <%= button_to "編集・削除", edit_tweet_path(tweet.id), method: :get, class: "button is-small is-outlined has-text-weight-semibold", style: "color: #7d7d7d; border-color: #7d7d7d;" %>
              </div>
            <% end %>
          </nav>
          <div class="content pl-4 mb-1">
            <p class="content mb-0 is-size-6"><%= tweet.updated_at.strftime("%Y年%_m月%_d日 %_H:%M") %></p>           
            <p class="content mb-0 is-size-6 is-underlined"><%= tweet.title %></p>
            <p class="content mb-0 is-size-6" ><%= tweet.content %></p>
          </div>
          <div class="content is-mobile pl-4 mb-2">
            <% if tweet.favorited_by?(current_user.id) %>
              <%= button_to "いいね #{tweet.favorites.size}", tweet_favorites_path(tweet.id), method: :delete, class: "button is-small has-text-weight-semibold has-text-white", style: "background-color: #6a994e" %>
            <% else %>
              <%= button_to "いいね #{tweet.favorites.size}", tweet_favorites_path(tweet.id), method: :post, class: "button is-small is-outlined has-text-weight-semibold", style: "color: #6a994e; border-color: #6a994e;" %>
            <% end %>
          </div>
        </div>
      </article>
      <% end %>
    </div>
  </div>
</main>