config/routes.rb
Rails.application.routes.draw do
  resources :users, only: %i[index new create show destroy edit update] do
    scope module: :users do
      resources :favorites, only: %i[index]
    end

    resource :relationships, only: %i[create destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :tweets, only: %i[index new create show destroy edit update] do
    resource :favorites, only: %i[create destroy]
  end

  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

  get '*path', controller: 'application', action: 'render_404'
  root to: 'sessions#new'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hitorigoto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
    <%= javascript_import_module_tag "custom/logout-modal" %>
      <%= yield(:js) %>
  </head>

  <body>
    <!-- ヘッダー -->
    <header class="navbar" style="background-color: #a7c957">
      <div class="navbar-brand">
        <span class="navbar-item is-size-3 has-text-weight-semibold" style="color: #386641">
          Hitorigoto
        </span>
      </div>

      <div class="navbar-end">
        <% if session[:user_id] %>
        <div class="navbar-item">
          <div class="tag is-medium has-text-weight-semibold" style="background-color: #a7c957">
            <p><%= current_user.email %>でログイン中</p>
            <button class="button is-rounded is-light has-text-weight-semibold ml-4" id="logout-button">ログアウト</button>
        </div>
        <% end %>
      </div>
    </header>

    <!-- タブ -->
    <div class="tabs is-small has-text-weight-semibold" style="background-color: #f2e8cf">
      <ul>
        <li><a href="<%= user_path(current_user.id) %>">マイページ</a></li>
        <li><a href="<%= new_tweet_path() %>">ひとりごと投稿</a></li>
        <li><a href="<%= tweets_path() %>">ひとりごと一覧</a></li>
        <li><a href="<%= users_path() %>">ユーザーリスト</a></li>
        <li><a href="<%= edit_user_path(current_user.id) %>">アカウント編集</a></li>
      </ul>
    </div>

    <!-- モーダルウインドウ -->
    <div class="modal" id="logout-modal-window">
      <div class="modal-background"></div>
      <div class="modal-content">
        <div class="column is-6 is-offset-3">
          <div class="box">
            <div class="content-level">
              <div class="level-left">
                <button class="delete" aria-label="close" id="close-modal-delete"></button>
              </div>
              <div class="level-item">
                <p>ログアウトしますか？</p>
              </div>
            </div>
            <div class="level mt-4">
              <div class="level-item">
                <%= button_to "はい", logout_path, method: :delete, class: "button is-rounded is-white is-inverted has-text-weight-semibold" %>
              </div>
              <div class="level-item">
                <button class="button is-rounded has-text-weight-semibold" aria-label="close" id="close-modal-cancel">いいえ</button>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <div class="container">
      <%= yield %>
    </div>
  </body>
  </div>
</html>

app/views/layouts/header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Hitorigoto</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.4/css/bulma.min.css">
    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
    <header class="navbar" style="background-color: #a7c957">
      <div class="navbar-brand">
        <span class="navbar-item is-size-3 has-text-weight-semibold" style="color: #386641">
          Hitorigoto
        </span>
      </div>
    </header>

    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>